#!/usr/bin/env python3

import hashlib
import urllib.request
import shutil
import os
from urllib.parse import urlparse
import sys
from platform import python_version

PYTHON_VERSION=python_version()
# if PYTHON_VERSION is None:
#     PYTHON_VERSION=PARSE_ERROR

PYTHON_USER_AGENT="python/" + PYTHON_VERSION + "/esg/4.3.2-20230405-191025/created/2023-04-11T17:26:15-06:00"

################################################################
#
# Climate Data Gateway download script
#
#
# Generated by: NCAR Climate Data Gateway
#
# Your download selection includes data that might be secured using API Token based
# authentication. Therefore, this script can have your api-token. If you
# re-generate your API Token after you download this script, the download will
# fail. If that happens, you can either re-download this script or you can replace
# the old API Token with the new one by going to the Account Home:
#
# https://www.earthsystemgrid.org/account/user/account-home.html
#
# and clicking on "API Token" link under "Personal Account". You will be asked
# to log into the application before you can view your API Token.
#
# Usage: python3 python-ucar.cgd.cesm2.b.e21.B1850.f09_g17.CMIP6-piControl.001.atm.proc.daily_ave.TREFHTMX-20230411T1726Z.py
# Version: 0.1.0-alpha
#
#
# Dataset
# ucar.cgd.cesm2.b.e21.B1850.f09_g17.CMIP6-piControl.001.atm.proc.daily_ave.TREFHTMX
# adf8d522-efb2-4cc9-8897-6ed2add6c8f0
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2.b.e21.B1850.f09_g17.CMIP6-piControl.001.atm.proc.daily_ave.TREFHTMX.html
# https://www.earthsystemgrid.org/dataset/id/adf8d522-efb2-4cc9-8897-6ed2add6c8f0.html
#
# Dataset Version
# 1
# 5a01f4ab-a2a6-4415-abf7-ccfa1d1ea035
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2.b.e21.B1850.f09_g17.CMIP6-piControl.001.atm.proc.daily_ave.TREFHTMX/version/1.html
# https://www.earthsystemgrid.org/dataset/version/id/5a01f4ab-a2a6-4415-abf7-ccfa1d1ea035.html
#
################################################################

print("This Python 3 download script is experimental.  Please provide feedback at 'esg-support@earthsystemgrid.org'.")
print("")

urls = [
     'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/timeseries-cmip6/b.e21.B1850.f09_g17.CMIP6-piControl.001/atm/proc/tseries/day_1/b.e21.B1850.f09_g17.CMIP6-piControl.001.cam.h1.TREFHTMX.13000101-13091231.nc?api-token=Gu6m2qV0xQkj1DGc11kbkEOeqcbcCa4VXlKXlYzF',
     'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/timeseries-cmip6/b.e21.B1850.f09_g17.CMIP6-piControl.001/atm/proc/tseries/day_1/b.e21.B1850.f09_g17.CMIP6-piControl.001.cam.h1.TREFHTMX.13100101-13191231.nc?api-token=Gu6m2qV0xQkj1DGc11kbkEOeqcbcCa4VXlKXlYzF',
     'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/timeseries-cmip6/b.e21.B1850.f09_g17.CMIP6-piControl.001/atm/proc/tseries/day_1/b.e21.B1850.f09_g17.CMIP6-piControl.001.cam.h1.TREFHTMX.13200101-13291231.nc?api-token=Gu6m2qV0xQkj1DGc11kbkEOeqcbcCa4VXlKXlYzF',
     'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/timeseries-cmip6/b.e21.B1850.f09_g17.CMIP6-piControl.001/atm/proc/tseries/day_1/b.e21.B1850.f09_g17.CMIP6-piControl.001.cam.h1.TREFHTMX.13300101-13391231.nc?api-token=Gu6m2qV0xQkj1DGc11kbkEOeqcbcCa4VXlKXlYzF',
     'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/timeseries-cmip6/b.e21.B1850.f09_g17.CMIP6-piControl.001/atm/proc/tseries/day_1/b.e21.B1850.f09_g17.CMIP6-piControl.001.cam.h1.TREFHTMX.13400101-13491231.nc?api-token=Gu6m2qV0xQkj1DGc11kbkEOeqcbcCa4VXlKXlYzF',
     'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/timeseries-cmip6/b.e21.B1850.f09_g17.CMIP6-piControl.001/atm/proc/tseries/day_1/b.e21.B1850.f09_g17.CMIP6-piControl.001.cam.h1.TREFHTMX.13500101-13591231.nc?api-token=Gu6m2qV0xQkj1DGc11kbkEOeqcbcCa4VXlKXlYzF',
     'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/timeseries-cmip6/b.e21.B1850.f09_g17.CMIP6-piControl.001/atm/proc/tseries/day_1/b.e21.B1850.f09_g17.CMIP6-piControl.001.cam.h1.TREFHTMX.13600101-13691231.nc?api-token=Gu6m2qV0xQkj1DGc11kbkEOeqcbcCa4VXlKXlYzF',
     'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/timeseries-cmip6/b.e21.B1850.f09_g17.CMIP6-piControl.001/atm/proc/tseries/day_1/b.e21.B1850.f09_g17.CMIP6-piControl.001.cam.h1.TREFHTMX.13700101-13791231.nc?api-token=Gu6m2qV0xQkj1DGc11kbkEOeqcbcCa4VXlKXlYzF',
     'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/timeseries-cmip6/b.e21.B1850.f09_g17.CMIP6-piControl.001/atm/proc/tseries/day_1/b.e21.B1850.f09_g17.CMIP6-piControl.001.cam.h1.TREFHTMX.13800101-13891231.nc?api-token=Gu6m2qV0xQkj1DGc11kbkEOeqcbcCa4VXlKXlYzF',
     'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/timeseries-cmip6/b.e21.B1850.f09_g17.CMIP6-piControl.001/atm/proc/tseries/day_1/b.e21.B1850.f09_g17.CMIP6-piControl.001.cam.h1.TREFHTMX.13900101-13991231.nc?api-token=Gu6m2qV0xQkj1DGc11kbkEOeqcbcCa4VXlKXlYzF']

# Gets filename even when there are parameters (but uses urlparse and os)
def get_filename(url):
    a = urlparse(url)
    return os.path.basename(a.path)

opener = urllib.request.build_opener()
opener.addheaders = [("User-agent", PYTHON_USER_AGENT)]
opener.addheaders.append(("Authorization", "api-token {}".format("Gu6m2qV0xQkj1DGc11kbkEOeqcbcCa4VXlKXlYzF")))

for url in urls:
    file_name = get_filename(url)

    print("Downloading File: ", url)

    try:
        file_name = os.path.join('/home/tcarrasco/result/data/LENS2/tmax/orig/CR/', file_name)
        with opener.open(url) as response, open(file_name, 'ab') as out_file:
            shutil.copyfileobj(response, out_file)

    except urllib.error.HTTPError as e:
    # Return code error (e.g. 404, 501, ...)
        print("HTTPError: {}".format(e.code))
    except urllib.error.URLError as e:
    # Not an HTTP-specific error (e.g. connection refused)
        print("URLError: {}".format(e.reason))
    else:
        # 200
        print("Success")